import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/base/Header";
import "../scss/main.scss";
import Footer from "@/components/base/Footer";
import Login from "@/components/auth/Login";
import Register from "@/components/auth/Register";

const nunito = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "UAE IPTV BOX - Best IPTV service in UAE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <Header />
        {children}
        <Footer />
        <Login />
        <Register />
      </body>
    </html>
  );
}
